data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/your_service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'retail-analytics-project'
    dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: //your api key id
  api_key_secret: // your api secret